name: test
on:
    push:
    pull_request:
jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
            - uses: pnpm/action-setup@v2
              with:
                  version: 9
            - name: Install modules
              run: pnpm install
            - name: Run tsc
              run: pnpm run tsc
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
            - uses: pnpm/action-setup@v2
              with:
                  version: 9
            - name: Install modules
              run: pnpm install
            - name: Run build
              run: pnpm run build
